# This is a basic workflow to help you get started with Actions

name: Test CI / CD

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: self-hosted
  #  env:
  #    GOPATH: "/root/go"
  #    GO111MODULE: off
  #  defaults:
     # run:
     #   working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    #steps:
   # - name: Checkout code
  #    uses: actions/checkout@v2
 #     with:
#        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
      env :
        GOPATH: "/root/go"
        HOME: "/root"
        GOROOT: "/root/usr/local/go"
        GOCACHE: "/root/.cache/go-build"
        GO111MODULE: off

    - name: Export Go gache
      run: export GOCACHE=$GOCACHE
      
    - name: Export Go gache
      run: export HOME=$HOME
    #- name: Export GO111MODULE
      #run: export GO111MODULE=off
    - name: go mods
      run: go mod init /root/actions-runner/test_ci/githubActionsTesting/githubActionsTesting
    - name: Build
      run: go build -v ./...

    - name: restart
      run: systemctl restart cicdtest.service
