# This is a basic workflow to help you get started with Actions#

name: Test CI / CD

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: self-hosted
   # env:
     # GOPATH: "/root/go"
  #    GO111MODULE: off
  #  defaults:
     # run:
     #   working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    #steps:
   # - name: Checkout code
  #    uses: actions/checkout@v2
 #     with:
#        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.6
  #    env :
  #      GOPATH: "/root/go"
  #      HOME: "/root"
  #      GOROOT: "/root/usr/local/go"
  #      GOCACHE: "/root/.cache/go-build"
  #      GO111MODULE: off

   # - name: Export Go cache
   #   run: export GOCACHE=$GOCACHE
      
   # - name: Export Go HOME
   #   run: export HOME=$HOME
      
   # - name: Expor Go Path
   #   run: export GOPATH=$GOPATH
      
   # - run: |
   #     export PATH=$PATH:$(go env GOPATH)/bin
   #     go get -u golang.org/x/lint/golint
    #    golint -set_exit_status ./...
      
   ## - name: Export GO111MODULE
     # run: export GO111MODULE=off

    - name: Build
      #run: go build -v ./...
      run: /usr/local/go/bin/go build
    - name: Reload Daemon
      run: systemctl daemon-reload
      
    - name: restart test service
      run: systemctl restart cicdtest.service

    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
        server_address: mail.gomarkho.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: ddaud@gomarkho.com
        # from email name
        from: Test CICD
